#!/bin/bash
# My first script
# Perform apt-get update and apt-get upgrade with a single command
# Only upgrades if there are packages to upgrade

sudo apt-get update
CHECK=$(sudo apt list --upgradeable)

if [ "$CHECK" != "Listing..." ]
    then echo "TIME TO UPGRADE!"; sudo apt-get upgrade
else
    echo $'NOTHING TO UPGRADE. \nGOODBYE.'
fi

# sudo apt-get upgrade
