#!/bin/bash
# My first script
# Perform apt-update and apt-upgrade with a single command
# Only upgrades if there are packages to upgrade

sudo apt update
CHECK=$(sudo apt list --upgradeable 2> /dev/null) 

if [ "$CHECK" != "Listing..." ]
    then echo $'TIME TO UPGRADE!\n'; sudo apt upgrade 
else
    echo $'\nNOTHING TO UPGRADE. \nGOODBYE.'
fi