#!/bin/bash
# My first script

sudo apt-get update
check=$(sudo apt list --upgradeable)

if [ $check != "Listing..." ]
    then echo "TIME TO UPGRADE!"; sudo apt-get upgrade
else
    echo $'NOTHING TO UPGRADE. \nGOODBYE.'
fi

# sudo apt-get upgrade
