#!/bin/bash
# My first script

sudo apt-get update


if [ $(sudo apt list --upgradeable) != "Listing..." ] 
    then echo "TIME TO UPGRADE!"; sudo apt-get upgrade
else
    echo $'NOTHING TO UPGRADE. \nGOODBYE.'
fi

#sudo apt-get upgrade
